apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nodejs-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: dev.chi
    http:
      paths:
      - path: /nodejs
        backend:
          serviceName: nodejs-web-service
          servicePort: 80